version: "3.8"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: "${NEXTAUTH_SECRET}"
      # 如果将来需要数据库，添加 DATABASE_URL: "postgresql://user:pass@db:5432/mydb"
    depends_on: []